name: NIReader
options:
  bundleIdPrefix: com.iraq
  createIntermediateGroups: true
targets:
  NIReader:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: NIReader
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.iraq.nireader
      PRODUCT_NAME: NIReader
      INFOPLIST_FILE: NIReader/App/Info.plist
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGN_IDENTITY: ""
      CODE_SIGNING_REQUIRED: NO
      AD_HOC_CODE_SIGNING_ALLOWED: YES
      SWIFT_VERSION: "5.9"

